"""Provider-independent research agent contracts and orchestration."""

from .contracts import (
    AgentDefinition,
    AgentProposal,
    BackendLocation,
    HypothesisProposal,
    ModelBackend,
    ModelRequest,
    ModelResponse,
    PredictionProposal,
    ResearchAgent,
)
from .coordination import CoordinatorProtocolError, CoordinatorSession
from .examination import ExaminationLimitError, PrivateExamination
from .independent import AgentProtocolError, IndependentPass
from .model_roles import (
    ModelCoordinator,
    ModelCrossDomainReviewer,
    ModelExaminer,
    ModelThinker,
    StructuredOutputError,
)
from .progress import ProgressCallback, ProgressEvent
from .roles import (
    Coordinator,
    CoordinatorReport,
    ExaminationChallenge,
    ExaminationDisposition,
    ExaminationExchange,
    ExaminationResult,
    Examiner,
    ExaminerReview,
    InvestigationPlan,
    ObservationDraft,
    Thinker,
    ThinkerProposal,
    ThinkerResponse,
    ThinkerTask,
)
from .runtime import ResearchCycle, ResearchCycleResult
from .telemetry import (
    ModelPricing,
    TrackedBackend,
    UsageRecord,
    UsageTotal,
    UsageTracker,
    openai_standard_pricing,
)
from .synthesis import (
    CrossDomainReviewer,
    CrossDomainSynthesis,
    FindingRelation,
    FindingRelationType,
    MinorityReport,
    PromotionCandidate,
    PromotionExecutor,
    PromotionRecord,
    SynthesisProtocolError,
    SynthesisSession,
)

__all__ = [
    "AgentDefinition",
    "AgentProposal",
    "AgentProtocolError",
    "BackendLocation",
    "Coordinator",
    "CoordinatorProtocolError",
    "CoordinatorReport",
    "CoordinatorSession",
    "CrossDomainReviewer",
    "CrossDomainSynthesis",
    "ExaminationChallenge",
    "ExaminationDisposition",
    "ExaminationExchange",
    "ExaminationLimitError",
    "ExaminationResult",
    "Examiner",
    "ExaminerReview",
    "FindingRelation",
    "FindingRelationType",
    "HypothesisProposal",
    "IndependentPass",
    "InvestigationPlan",
    "MinorityReport",
    "ObservationDraft",
    "ModelBackend",
    "ModelCoordinator",
    "ModelCrossDomainReviewer",
    "ModelExaminer",
    "ModelRequest",
    "ModelResponse",
    "ModelThinker",
    "PredictionProposal",
    "PrivateExamination",
    "PromotionCandidate",
    "PromotionExecutor",
    "PromotionRecord",
    "ResearchAgent",
    "ResearchCycle",
    "ResearchCycleResult",
    "StructuredOutputError",
    "SynthesisProtocolError",
    "SynthesisSession",
    "Thinker",
    "ThinkerProposal",
    "ThinkerResponse",
    "ThinkerTask",    "ModelPricing",    "ProgressCallback",    "ProgressEvent",    "TrackedBackend",    "UsageRecord",    "UsageTotal",    "UsageTracker",    "openai_standard_pricing",
]
